automation-tower-chinese-translations.html
automation-tower-japanese-translations.html
automation-tower-korean-translations.html
automation-tower-prior-versions.html

Adds the following:
- 4.1.4 (English, Japanese, Chinese)
- 4.2.1 (Japanese, Chinese, Korean)
- 4.1.3 (Japanese, Chinese)
Marked the following versions as EOL'd:
- 4.0 and 4.0.1 where applicable
- 3.7.x and older where applicable
See rendered content:
- http://docs.testing.ansible.com/automation-tower-prior-versions.html
- http://docs.testing.ansible.com/automation-tower-japanese-translations.html
- http://docs.testing.ansible.com/automation-tower-chinese-translations.html
- http://docs.testing.ansible.com/automation-tower-korean-translations.html

Adds  4.1.4 and missing versions from Ja, Zh, and Ko

---

.github/workflows/publish-package-docs.yaml

Resolves issue #131 and relates to: https://github.com/ansible-community/community-topics/issues/174
Here's a screen of the inputs for kicking off the publishing workflow: 
There are some workflow runs on my fork at: https://github.com/oraNod/docsite/actions/workflows/publish-package-docs.yaml

Action to build package docs

---

.github/workflows/publish-package-docs.yaml

Update the workflow to use working-directory for requirements and create separate steps for project and docsite requirements.

Separate requirements steps

---

personas/ansible-docsite-personas.md

Based on feedback collected in https://github.com/ansible-community/community-topics/issues/175
In particular:
- Haven't we [agreed](https://github.com/ansible-community/community-topics/issues/175#issuecomment-1404755361) not to treat `Operators` as a separate category but rather a sub-category of users? See the suggested changes
- Based on Sandra's [comment](https://github.com/ansible-community/community-topics/issues/175#issuecomment-1400812701) (+1 from me), we can include the quick-link for experts. See the suggested changes

ansible-docsite-personas.md: re-define the page based on feedback collected so far

---

ecosystem.html

This PR migrates Ansible Sign documentation links on the ecosystem page to RTD.

Point to RTD for Ansible Sign documentation

---

data/ecosystem.yaml

Change the url for the AWX Operator docs to point to https://ansible.readthedocs.io/projects/awx-operator/en/latest/

update awx operator docs home

---

data/ecosystem.yaml

Remove pinakes from the current ecosystem
It has not been updated in 10 months, its not in current development, and not planned to be developed further. In addition while the parts that work are good, it still has a good handful of non working features, it is still in tech preview. 
While the Repo should stay, we should likely take it off the current Ecosystem docsite.

Update ecosystem.yaml to remove pinakes

---

data/ecosystem.yaml

Fix the link to AWX docs from the ecosystem page (https://docs.ansible.com/ecosystem.html).
Fixes #190

Issue 190 Fix link to AWX docs in ecosystem page

---

README.md

IRC on libra chat has been discontinued and now we are redirecting community to Forum.

Replaced IRC with the Forum on the README.md

---

templates/404.html
templates/_base.html
templates/ansible-prior-versions.html
templates/ansible_community.html
templates/automation-tower-chinese-translations.html
templates/automation-tower-japanese-translations.html
templates/automation-tower-korean-translations.html
templates/automation-tower-prior-versions.html
templates/community.html
templates/core-translated-ja.html
templates/core.html
templates/developers.html
templates/ecosystem.html
templates/maintainers.html
templates/platform.html
templates/users.html

This makes it much easier to see what's going on with multiple tabs open.
For example:
Before:
> Ansible Documentation
After:
> Users | Ansible Documentation

Add specific titles for each page

---

data/ecosystem.yaml

Remove receptor from ecosystem

---

data/ecosystem.yaml

This PR changes "Ansible Pylibssh" to "pylibssh" on the ecosystem page.

fix pylibssh naming

---

.htaccess

This PR redirects the old "automation.html" page in a consistent way with redirects to redhat.com urls on the community website: https://www.redhat.com/en/technologies/management/ansible

redirect automation to redhat.com

---

templates/404.html
templates/_base.html
templates/_footer.html
templates/_scripts.html
templates/ansible-prior-versions.html
templates/ansible_community.html
templates/community.html
templates/core-translated-ja.html
templates/core.html
templates/ecosystem.html

This change prevents relative links to assets such as css files that can result in issues with site crawlers.

prepend the base url to site assets

---

robots.txt

This PR updates the robots.txt file to disallow crawlers on URLs for old projects and for pages that no longer exist.

update robots.txt to disallow old urls

---

data/ecosystem.yaml

The repo was archived and subsumed into vscode repo so removing it here.

remove als from ecosystem page

---

.htaccess

Addresses issue #240 so that users with bookmarks to old pages for 4.5 or "latest" will be redirected to the index page for instructions on where content moved to.

Adds redirects for controller docs already migrated down/upstream

---

noxfile.py

This change results in the paths of the output and input files relative to the project directory when pip-compiling requirements.

make pip compile req file path relative to project

---

README.md
data/community.yaml
data/maintainers.yaml
data/pages.yaml

Tidy up a bit to remove old links with the appropriate forum links.

Replace old links with forum links

---

.htaccess

This change removes the redirects for the community ee content. Should be merged after this PR is integrated and docs are back -> https://github.com/ansible/ansible-documentation/pull/1852

rm community ee redirects

---

templates/_scripts.html

Fixes #263 
This change replaces `scripts.min.js` that was previously available from HubSpot with the Bootstrap alternative. 
Apparently we missed the `.js` stuff when we added the minified css: https://github.com/ansible/docsite/commit/3f98e6642c1ce27464f17ca1306414442cd904d2

Restore hamburger menus

---

data/ecosystem.yaml
data/pages.yaml
templates/ecosystem.html

reverts 27eeb61926f3c3d2e85660d45f7a251537c0bea2 and restores the ecosystem page in the docsite

add projects back to the ecosystem

---

.github/dependabot.yml

Looking at the logs from this dependabot run: https://github.com/ansible/docsite/actions/runs/14000128009/job/39204494666
It seems dependabot is having trouble finding the requirements:
```
updater | 2025/03/21 20:14:56 WARN <job_984669263> Please check your configuration as there are groups where no dependencies match:
- pip
This can happen if:
- the group's 'pattern' rules are misspelled
- your configuration's 'allow' rules do not permit any of the dependencies that match the group
- the dependencies that match the group rules have been removed from your project
```
And then further down...
```
updater | 2025/03/21 20:14:56 WARN <job_984669263> Skipping update group for 'pip' as it does not match any allowed dependencies.
updater | 2025/03/21 20:14:56 INFO <job_984669263> Found no …
```

update reqs dir in dependabot config

---

data/controller_archive.yaml

This will allow the https://docs.ansible.com/automation-tower-prior-versions.html page to show updated list of older versions.

Add 4.5 to the list of archived controller doc versions

---

data/platform.yaml

Noticed the description on the `platform.html` page is not quite correct:

update controller archive description

---

requirements/pip-tools.txt

The changes in https://github.com/ansible/docsite/pull/276/files don't look quite right. I used `nox -s "pip-compile-3.11(pip-tools)" -- --upgrade-package=setuptools` instead.

bump setuptools

---

.htaccess
index-archive.html

The index-archive page is required to set up the web server for the legacy-controller-docs subdomain.
See https://forum.ansible.com/t/we-re-moving-to-read-the-docs/43519/2#p-132529-creating-a-separate-landing-page-5

create the index-archive page
