ansible/docsite

- core.html
Include Ansible Test in the core.html page.
> Add ansible test

- .github/workflows/publish-package-docs.yaml
Adds a workflow step to rsync package docs build to a web server directory.
> deploy demo doc build

- user-journeys/ansible-user-journey-maps.md
This PR adds user journeys with mermaidJS to extend the Ansible docsite personas
> create user journey maps

- user-journeys/ansible-user-journey-maps.md
I don't know mermaid syntax so just dumping in all the top tasks I could think of for the personas so we have the basis for reviews by community folks
> add top tasks for all personas

- personas/ansible-docsite-personas.md
@Andersson007 A few edits on top of your PR to the personas doc. Note that I dropped the last line because it seems a little out of place imo. Thanks.
> minor nits to personas

- user-journeys/ansible-user-journey-maps.md
Capturing first set of complete user journeys for the Ansible docsite personas.
> User journeys for Ansible docsite personas

- ansible-prior-versions.html
- automation-tower-chinese-translations.html
- automation-tower-japanese-translations.html
- automation-tower-korean-translations.html
- automation-tower-prior-versions.html
- community.html
- core-translated-ja.html
- core.html
- developers.html
- ecosystem.html
- index.html
- maintainers.html
- platform.html
- static/css/main.css
- users.html
Fixes https://github.com/ansible/docsite/issues/161 https://github.com/ansible/docsite/issues/162 https://github.com/ansible/docsite/issues/160 https://github.com/ansible/docsite/issues/141
> Add quicklinks and update ecosystem

- data/journeys/docsite-journeys.md
Update personas journeys based on all the refactoring we did in the jinja-docsite repo
> data/journeys: Update docsite-journeys.md

- automation-tower-chinese-translations.html
- automation-tower-japanese-translations.html
- automation-tower-korean-translations.html
- automation-tower-prior-versions.html
Replaces https://github.com/ansible/docsite/pull/166 with updates for new layout.
> Add tower 4.2.2 translations

- ansible-prior-versions.html
- ansible_community.html
- automation-tower-chinese-translations.html
- automation-tower-japanese-translations.html
- automation-tower-korean-translations.html
- automation-tower-prior-versions.html
- community.html
- core-translated-ja.html
- core.html
- developers.html
- ecosystem.html
- maintainers.html
- oldsite/ansible_community.html
- oldsite/automation-tower-chinese-translations.html
- oldsite/automation-tower-japanese-translations.html
- oldsite/automation-tower-korean-translations.html
- oldsite/automation-tower-prior-versions.html
- platform.html
- users.html
Batch of updates from these issues:
- https://github.com/ansible/docsite/issues/170 
- https://github.com/ansible/docsite/issues/169
- https://github.com/ansible/docsite/issues/168
> Batch of updates to the docsite pages

- .htaccess
Fixes ##129
Part of https://github.com/ansible/ansible/issues/80885
> redirect moved compile page

- automation-tower-chinese-translations.html
- automation-tower-japanese-translations.html
- automation-tower-korean-translations.html
Corresponds to https://github.com/ansible/jinja-docsite/pull/119
> update 4.3 in translated versions

- .htaccess
Follows up on https://github.com/ansible/ansible-documentation/pull/617
> redirect ee getting started docs

- data/ecosystem.yaml
Resolves: https://github.com/ansible/docsite/issues/194 
Related to https://github.com/ansible/ecosystem-documentation/pull/15
> rm galaxy from ecosystem

- data/ecosystem.yaml
- data/pages.yaml
- templates/core.html
Issue #206 
- Update the ecosystem page so test is included with core
- Separate data fields for the core page from the ecosystem page
> Update ecosystem page: reference to Ansible Test

- data/controller_archive.yaml
- data/controller_i18n_links.yaml
Added 4.4 to archives and added 4.5 for ja, ko, and zh pages.
> Updated w/ 4.4 (prior) & added 4.5 translated versions.

- data/ecosystem.yaml
This PR adds several projects to the current ecosystem page and relates to https://github.com/ansible/ecosystem-documentation/pull/27
> update ecosystem with dev tool projects

- data/ecosystem.yaml
Follows up on https://github.com/ansible/docsite/pull/211#discussion_r1442014876
> ansible-pylibssh yaml key

- .github/dependabot.yml
Follows up on #230 by grouping dependency updates for actions.
> group dependency bumps for actions

- ansible-sitemap.xml
Part of https://github.com/ansible/ansible-documentation/issues/1250
> update Ansible docs sitemap for Ansible 10

- sass/_ansible-banner.scss
- sass/_colors.scss
- templates/_ansible-banner.html
This PR updates the banner to make it more obvious and less of a navbar. The changes also improve accessibility by increasing the color contrast for the text and background image so that it passes all tests according to https://webaim.org/resources/contrastchecker/
Here is a screengrab of how it renders:
> improve banner and accessibility

- templates/_base.html
Follows up on https://github.com/ansible/docsite/pull/257 and https://github.com/ansible/ansible-documentation/pull/2132
> rm survey banner

- requirements/requirements.txt
created by  running nox -s "pip-compile-3.11(requirements)"
> run requirements updates
